### ISSUE TITLE
Dead/HTTP Error 404 Not Found links at DKRZ

### ISSUE THREAD

**Issue by valeriupredoi** [IS-ENES3/IS-ENES-Website#2]
I am using the links scanner from https://github.com/valeriupredoi/check_links_in_site and found two dead links:

WARNING: https://www.dkrz.de/daten-en/wdcc?set_language=en gives HTTP Error 404: Not Found
WARNING: https://www.dkrz.de/daten-en/data-services/Datapublication gives HTTP Error 404: Not Found

**Comment by valeriupredoi** [comment]
Kerstin says: These broken links you found must be really old - we changed the website
structure underlying these links around 2015 and I guess the content of
the page also changed several times since then, thus I do not know,
which content was once linked, and where it is now...
You could try to contact the author of the pages, where these links are
referenced to find out what the content of these links were and then I
could try to help to find a proper link on our pages.... or you simply
mark the links as "outdated" ;-)

@SophieMacadamia @fannyadloff please advise what to do with these links :beer:

**Comment by fannyadloff** [comment]
I will contact someone at DKRZ and ask.

**Comment by valeriupredoi** [comment]
awesome, cheers much, Fanny! I mean, we could just forget about them, here are the latest test results https://github.com/IS-ENES3/Tests/runs/7244006560?check_suite_focus=true - note that the MPIMET one actually works, it just returns a 404 (maybe we should tell them?) - few links that are broken, and they stay the same, all good by me to be fair :beer:

**Comment by fannyadloff** [comment]
Hi V,

The 2 links from DKRZ (previous message) should be replaced by:
(1) https://wdc-climate.de/
(2) https://docs.dkrz.de/doc/dataservices/publishing_dissemination/index.html

**Comment by valeriupredoi** [comment]
great, thanks a lot @fannyadloff :beer: Let me change them and rerun the test!

**Comment by fannyadloff** [comment]
For the MPI one, it works for me without a 404!

**Comment by valeriupredoi** [comment]
yes, I just whitelisted that so the test doesn't complain - it does return a 404 if polled from a script though (so their page is just a *bit* broken haha)

**Comment by valeriupredoi** [comment]
and now we don't have any more broken links https://github.com/IS-ENES3/Tests/actions/runs/2636040080 - yay, cheers guys! :partying_face:
