### ISSUE TITLE
Dead links pointing to the old ENES Portal

### ISSUE THREAD

**Issue by valeriupredoi** [IS-ENES3/IS-ENES-Website#5]
@SophieMacadamia here are a few dead links that are currently pointing to the **old** ENES Portal site:

ERROR: https://portal.enes.org/community/community-workshops/fifth-workshop-on-coupling-technologies-for-earth-system-models gives HTTP Error 404: Not Found
ERROR: https://portal.enes.org/community/announcements/events/joint-is-enes3-esiwace2-virtual-workshop-on-new-opportunities-for-ml-and-ai-in-weather-and-climate-modelling gives HTTP Error 404: Not Found
ERROR: https://portal.enes.org/community/community-workshops/7th-enes-hpc-workshop-barcelona-2022 gives HTTP Error 404: Not Found

If you tell me which are the new ones on the new portal then I will change them :beer:

**Comment by valeriupredoi** [comment]
the good news is that, after deploying to the perm site, these and the DKRZ links from https://github.com/IS-ENES3/IS-ENES-Website/issues/2 are the only broken links :grin:

**Comment by fannyadloff** [comment]
Hi Valeriu,
I think these are the links:
(1) https://is-enes3.github.io/IS-ENES-Portal-Website/coupling-workshops-detailed#CW2020
(2) https://is.enes.org/workshops-detailed/#ML-AI-WS
(3)  for this one, I need to clarify something with Sophie to prevent redundancy.

**Comment by valeriupredoi** [comment]
@fannyadloff you can find out where they are using `grep` e.g.

```bash
valeriu@valeriu-PORTEGE-Z30-C:~/IS-ENES-Website$ grep "https://portal.enes.org/community/community-workshops/fifth-workshop-on-coupling-technologies-for-earth-system-models" -r pages
pages/presentations-posters.md:[Fifth Workshop on Coupling Technologies for Earth System Models (CW2020)](https://portal.enes.org/community/community-workshops/fifth-workshop-on-coupling-technologies-for-earth-system-models) | ENES Portal Link
```

so that is linked from `presentations-posters.md` :beer:

**Comment by valeriupredoi** [comment]
> Hi Valeriu, I think these are the links: (1) https://is-enes3.github.io/IS-ENES-Portal-Website/coupling-workshops-detailed#CW2020 (2) https://is.enes.org/workshops-detailed/#ML-AI-WS (3) for this one, I need to clarify something with Sophie to prevent redundancy.

indeed those the links, can we change them to existing ones on the portal.enes.org or we just dump them?

**Comment by fannyadloff** [comment]
No, we should change them to the one I gave you above.

For (3) it's: https://portal.enes.org/hpc-workshops-detailed/#hpc7

I can't do a grep on github.
(I don't have a local repository)..
If you tell me where (2) and (3) are, I'll change them!

Same for the brocken DKRZ links.

**Comment by fannyadloff** [comment]
I fixed (1) & (2), can't find where is (3) located?

**Comment by valeriupredoi** [comment]
that's a ghost, I reran the test and it didn't show up anymore, must be @SophieMacadamia fixing the page in the meantime :grin: Brilliant, cheers @fannyadloff - no more broken links from the Portal :partying_face:
