### ISSUE TITLE
Redirection from old (e.g. event) URLs to relevant new locations

### ISSUE THREAD

**Issue by sadielbartholomew** [IS-ENES3/IS-ENES-Website#6]
Hi, I've noticed some old links to event pages have broken after the website revamp and though I can find the pages containing the equivalent information by going to the `https://is.enes.org/` homepage and navigating my way through the menu which is pretty self-explanatory (so nice job there!), which is a working solution, it would be ideal if the old links could be re-directed to the URL location for the corresponding new page. That way any old links on resources will not have to be updated, and it makes it easier and quicker for people viewing the site to find what they need based on previous known URLs.

For example, the page that described the Second General Assembly workshop, and linked to the e.g. presentation resources for it, was previously available at [`https://is.enes.org/events/workshops/is-enes3-virtual-2nd-general-assembly`](https://is.enes.org/events/workshops/is-enes3-virtual-2nd-general-assembly), now broken, and I found via the menu the corresponding page on the revamped page at [`https://is.enes.org/workshops-detailed/#isenes3ga2`](https://is.enes.org/workshops-detailed/#isenes3ga2). If you could create a mapping of all old pages to new ones, e.g. the former link quoted here to the latter, then set up redirection, that would be really useful.

Would this be possible at all? If it is, and is not on the cards, please can you consider this a user (i.e. website consulter/reader) request?

**Comment by valeriupredoi** [comment]
@sadielbartholomew this is such an old issue I am embarrassed to have replied only now - if I'm not tagged then chances are I will have ignored it for decades :laughing: I think you and @SophieMacadamia can figure that out together - Sophie has restructured the whole thing, and moved things a bit around, but has ported everything from olde site - well, everything that was deemed important

**Comment by valeriupredoi** [comment]
Closing as completed
