### ISSUE TITLE
Please setup site for enes.org and www.enes.org

### ISSUE THREAD

**Issue by gvde** [IS-ENES3/IS-ENES-Website#7]
Someone creative set up a github site for enes.org and www.enes.org. As enes.org was pointing to the github.io IPs it showed the content of https: / / github . com / heets 9862 / enes.org

**Comment by valeriupredoi** [comment]
hi @gvde my apologies I am only replying now - do you still need help with that? Note that we can't really help if we don't have admin rights to the Github repo where the pages are hosted - maybe @SophieMacadamia or @fannyadloff have? Cheers :beer:

**Comment by gvde** [comment]
@valeriupredoi The spam repo has been closed by github after my complaint.

This still leaves the issue, that enes.org hasn't been set up. I have removed the DNS RR for enes.org and www.enes.org once I have noticed the spam site.

So now http://enes.org/ or http://www.enes.org/ doesn't exist anymore. I don't know if that's good.

You have only set up is.enes.org and portal.enes.org but never enes.org/www.enes.org which was then hijacked.

**Comment by valeriupredoi** [comment]
ah gotcha! portal.enes.org is the new ENES portal that we (@SophieMacadamia @fannyadloff and myself) have ported and fully rebuilt/revamped (via GH Pages) from the old site. The old site was hosted at DKRZ and they should have deleted the domain name - note that I don't work for DKRZ nor do I have any admin rights there. Sorry to hear there were issues with the old domain name, but we had nothing to do with it, neither before the porting, nor after. Is there anything you'd like us to do? Cheers :beer:

**Comment by gvde** [comment]
@valeriupredoi I work at DKRZ. I made the DNS change to point the names to github. At that time, I was told to point enes.org/www.enes.org to github as well, because it was retired on our servers together with the portal/is sites.

I don't know how the communication worked. I just did what Kerstin told me to do. If noone claims it, then I won't set it up and it doesn't exist...

**Comment by valeriupredoi** [comment]
@gvde clearly there was a breakage or two in the communications chain - the Portal has been nicely sitting at portal.enes.org with its own GH repo here https://github.com/IS-ENES3/IS-ENES-Portal-Website - I am not sure why Kerstin didn't ask you to retire the old domain since we had agreed this new domain at the point of moving the site and data. At any rate, good thing things are taken care of now, please get back to us if there are any more issues (also feel free to reopen the issue) :+1:

**Comment by valeriupredoi** [comment]
hi @gvde just a heads up there is still a bit of metadata on enes.org - even if the site is now inaccessible, by posting the link on a social media platform eg Facebook, the browser will fill this for a header - no idea how you guys can delete it completely, sorry, but thought I'd tell you in case it's useful :+1: 
![Screenshot_20230303-165725~2](https://user-images.githubusercontent.com/28983971/222781854-3ca0853c-3bc4-4d76-b219-9a4305a135bb.jpg)

**Comment by gvde** [comment]
> hi @gvde just a heads up there is still a bit of metadata on enes.org

It's not metadata but caches. And the internet never forgets. On archive.org it'll probably be forever.

We keep the names disconnected although it's unfortunate. I generally find it better if the domain name and the standard www server name point to a working server, even if it's a simple page redirecting someplace else...
